import type { Metadata } from "next";
import { Geist, Geist_Mono, Smooch_Sans } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Suspense } from "react";
import ReactQueryProvider from "@/redux/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const smoochSans = Smooch_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-smooch-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={smoochSans.variable}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${smoochSans.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Suspense
            fallback={
              <div className="w-full h-screen flex justify-center items-center">
                Loading...
              </div>
            }
          >
            <ClientLayout>{children}</ClientLayout>
            <ToastContainer
              position="top-right" // koi bhi valid value dalo (e.g. top-right)
              // className="!top-1/2 !right-4 -translate-y-1/2"
            />{" "}
          </Suspense>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
